version: '3.8'
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 'app:app'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  celery:
    build: .
    command: celery -A celery_app.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
volumes:
  pgdata:
